[package]
name = "kgg"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
humantime = "2.2.0"
humantime-serde = "1.1.1"
rocket = { version = "0.5.1", features = ["json"] }
serde_json = "1.0.140"
